name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable
        options: >-
          --privileged
          --network host
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        run: echo "${{ secrets.CI_REGISTRY_PASSWORD }}" | docker login ${{ secrets.CI_REGISTRY }} -u "${{ secrets.CI_REGISTRY_USER }}" --password-stdin

      - name: Build Docker Image
        run: |
          echo "Building docker image..."
          docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} .
          docker push ${{ secrets.DOCKER_IMAGE_NAME }}
          mkdir reports
          docker save -o reports/build.tar ${{ secrets.DOCKER_IMAGE_NAME }}
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-tar
          path: reports/build.tar

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python Environment
        run: |
          python -m venv .env
          source .env/bin/activate
          pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Run Linter
        run: |
          echo "Running linter..."
          ruff check . --output-format json --output-file reports/lint.json
      
      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-json
          path: reports/lint.json

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python Environment
        run: |
          python -m venv .env
          source .env/bin/activate
          pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Run Tests
        run: |
          echo "Running tests..."
          pytest --cov-report html:reports/tests
      
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/tests/*
